CREATE TABLE IF NOT EXISTS links (
    hash TEXT PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);